### ISSUE TITLE
How to handle go modules

### ISSUE THREAD

**Issue by john8329** [OneOfOne/struct2ts#10]
I'm trying to run this tool as a go generator like this:

```go
//go:generate go run github.com/OneOfOne/struct2ts/cmd/struct2ts my.path/my_pkg.ServerInfoResponse -o ./MOD.ts
```

Yet it fails, as it can't resolve the module via HTTP. It's not published, and even if it was, I wouldn't want it to resolve the repository, I would like to get the code from the current source.

I'm running the command from inside the module directory, but it seems to make no difference, as the executable is ran in a temporary folder by `go run`.

How should I approach this? My aim is to automatically generate typescript interfaces when compiling the relative go structures.

Thanks

**Comment by OneOfOne** [comment]
I haven't had a chance to switch to a module-aware AST parser yet, I'll look into it soon.

**Comment by john8329** [comment]
Cool. In the meantime I solved it by generating the go code and implementing a custom tool. It works fine (except some issues with `interface {}` which doesn't map to `any`)

**Comment by OneOfOne** [comment]
@j0hnwhyte I tried to reproduce locally (created a new module, not published anywhere, added a struct to it and added `//go:generate go run github.com/OneOfOne/struct2ts/cmd/struct2ts mm.Struct -o go.ts`.

It worked fine with no errors (however `github.com/OneOfOne/struct2ts` was automatically added to `go.mod`).

Is there anything you can help me with to reproduce the bug?

**Comment by john8329** [comment]
`//go:generate go run github.com/OneOfOne/struct2ts/cmd/struct2ts apps_api.ModuleInfoResponse -o test.ts`
```
~/S/P/M/m/s/apps-api> go generate .
main.go:112: executing: go run /var/folders/tx/mswfphrj5m5gcg2bm22_0fh00000gn/T/s2ts_gen_1547754505988507000_5577006791947779410.go
# command-line-arguments
/var/folders/tx/mswfphrj5m5gcg2bm22_0fh00000gn/T/s2ts_gen_1547754505988507000_5577006791947779410.go:51:8: undefined: apps_api
main.go:119: exit status 2
```

I actually don't get how it's going to resolve the module dependencies from the temporary folder. Also I'm relatively new to this world, so I might be missing something obvious.

**Comment by OneOfOne** [comment]
Did you run `go mod init` before you run `go generate`?

It seems to work fine as long as `go.mod` file exists and the package name matches.

```
┏━ oneofone@Ava ❰/t/apps_api❱ 
┗━● pwd
/tmp/apps_api
┏━ oneofone@Ava ❰/t/apps_api❱ 
┗━● cat main.go 
//go:generate go run github.com/OneOfOne/struct2ts/cmd/struct2ts apps_api.ModuleInfoResponse -o test.ts
package apps_api
type ModuleInfoResponse struct {
Response string
}
┏━ oneofone@Ava ❰/t/apps_api❱ 
┗━● go generate
main.go:113: executing: go run /tmp/s2ts_gen_1547779270586907792_5577006791947779410.go
# command-line-arguments
../s2ts_gen_1547779270586907792_5577006791947779410.go:52:8: undefined: apps_api
main.go:120: exit status 2
┏━ oneofone@Ava ❰/t/apps_api❱
┗━● go mod init apps_api
go: creating new go.mod: module apps_api
┏━ oneofone@Ava ❰/t/apps_api❱
┗━● go generate
go: finding github.com/OneOfOne/struct2ts/cmd/struct2ts latest
go: finding github.com/OneOfOne/struct2ts/cmd latest
go: finding golang.org/x/tools/imports latest
go: finding golang.org/x/tools latest
go: finding github.com/alecthomas/units latest
go: finding github.com/alecthomas/template latest
main.go:112: executing: go run /tmp/s2ts_gen_1547779293072193582_5577006791947779410.go
┏━ oneofone@Ava ❰/t/apps_api❱
┗━● ack Response test.ts
// struct2ts:apps_api.ModuleInfoResponse
class ModuleInfoResponse {
      Response: string;
      this.Response = ('Response' in d) ? d.Response as string : ''; 
      ModuleInfoResponse,
```

**Comment by john8329** [comment]
Uhmm.. I have the module declaration, it's just that the package i'm taking the struct from is in a subfolder. I did some tests but they all failed.

```
Frankenstein:mf-server jwhite$ cd src/
Frankenstein:src jwhite$ ls
admin-api       apps-api        ctx             data            go.mod          go.sum          main.go         models          module          security        server          test.ts         utils
Frankenstein:src jwhite$ cd apps-api/
Frankenstein:src jwhite$ ls apps-api/
app-api.go              app.go                  gen-ts-modules.sh       info.go                 interfaces.go
Frankenstein:src jwhite$ head main.go 
package main

//go:generate go run github.com/OneOfOne/struct2ts/cmd/struct2ts jwhite.com/mf-server/apps_api.ModuleInfoResponse -o test.ts

import (
        "github.com/gin-gonic/gin"
        "jwhite.com/mf-server/ctx"
        "jwhite.com/mf-server/server"
        "os"
        // "github.com/pborman/getopt/v2"
Frankenstein:src jwhite$ head go.mod 
module jwhite.com/mf-server

require (
        github.com/OneOfOne/struct2ts v1.0.2 // indirect
        github.com/a-h/hsts v0.0.0-20170713145656-509101faf0de
        github.com/alecthomas/template v0.0.0-20160405071501-a0175ee3bccc // indirect
        github.com/alecthomas/units v0.0.0-20151022065526-2efee857e7cf // indirect
        github.com/appleboy/gin-jwt v2.5.0+incompatible
        github.com/ghodss/yaml v1.0.0
        github.com/gin-contrib/cors v0.0.0-20190101123304-5e7acb10687f
Frankenstein:src jwhite$ go generate
main.go:112: executing: go run /var/folders/tx/mswfphrj5m5gcg2bm22_0fh00000gn/T/s2ts_gen_1547811290179036000_5577006791947779410.go

...waiting a lot here...

build command-line-arguments: cannot load jwhite.com/mf-server/apps_api: cannot find module providing package jwhite.com/mf-server/apps_api
main.go:119: exit status 1
Frankenstein:src jwhite$ 
```

**Comment by OneOfOne** [comment]
I *think* it's because the folder is called `apps-api` but the path is `apps_api`

```
Frankenstein:src jwhite$ ls
admin-api       apps-api  <<<<<       ctx             data            go.mod          go.sum 

vs 

jwhite.com/mf-server/apps_api <<<
```

**Comment by john8329** [comment]
You may be right, having it this way makes it work a bit more. I'll dig into this obscure issue.

```
Frankenstein:src  jwhite$ go run github.com/OneOfOne/struct2ts/cmd/struct2ts mc128k.com/mf-server/apps-api.ModuleInfoResponse -o test.ts
main.go:87: querying module cache matches: go [list -e -json -compiled -test=false -export=false -deps=false -find=true -- github.com/derekparker/delve/service/api github.com/swaggo/gin-swagger/example/api github.com/beego/bee/cmd/commands/api github.com/astaxie/beego/plugins/apiauth github.com/go-openapi/jsonreference github.com/go-openapi/jsonpointer github.com/go-openapi/swag github.com/go-openapi/spec github.com/swaggo/swag/example/basic/api github.com/json-iterator/go/api_tests google.golang.org/genproto/protobuf/api google.golang.org/genproto/googleapis/api google.golang.org/genproto/googleapis/bytestream google.golang.org/genproto/googleapis/api/metric google.golang.org/genproto/googleapis/api/annotations google.golang.org/genproto/googleapis/api/monitoredres google.golang.org/genproto/googleapis/api/httpbody google.golang.org/genproto/googleapis/api/label google.golang.org/genproto/googleapis/api/serviceconfig google.golang.org/genproto/googleapis/api/distribution google.golang.org/genproto/googleapis/api/configchange google.golang.org/genproto/googleapis/longrunning google.golang.org/genproto/googleapis/api google.golang.org/genproto/googleapis/bytestream google.golang.org/genproto/googleapis/longrunning google.golang.org/genproto/googleapis/api/httpbody google.golang.org/genproto/googleapis/api/monitoredres google.golang.org/genproto/googleapis/api/annotations google.golang.org/genproto/googleapis/api/metric google.golang.org/genproto/googleapis/api/distribution google.golang.org/genproto/googleapis/api/label google.golang.org/genproto/googleapis/api/configchange google.golang.org/genproto/googleapis/api/serviceconfig google.golang.org/genproto/protobuf/api]: exit status 1: go: github.com/derekparker/delve@v1.0.0: module lookup disabled by GOPROXY=off
go: error loading module requirements
panic: querying module cache matches: go [list -e -json -compiled -test=false -export=false -deps=false -find=true -- github.com/derekparker/delve/service/api github.com/swaggo/gin-swagger/example/api github.com/beego/bee/cmd/commands/api github.com/astaxie/beego/plugins/apiauth github.com/go-openapi/jsonreference github.com/go-openapi/jsonpointer github.com/go-openapi/swag github.com/go-openapi/spec github.com/swaggo/swag/example/basic/api github.com/json-iterator/go/api_tests google.golang.org/genproto/protobuf/api google.golang.org/genproto/googleapis/api google.golang.org/genproto/googleapis/bytestream google.golang.org/genproto/googleapis/api/metric google.golang.org/genproto/googleapis/api/annotations google.golang.org/genproto/googleapis/api/monitoredres google.golang.org/genproto/googleapis/api/httpbody google.golang.org/genproto/googleapis/api/label google.golang.org/genproto/googleapis/api/serviceconfig google.golang.org/genproto/googleapis/api/distribution google.golang.org/genproto/googleapis/api/configchange google.golang.org/genproto/googleapis/longrunning google.golang.org/genproto/googleapis/api google.golang.org/genproto/googleapis/bytestream google.golang.org/genproto/googleapis/longrunning google.golang.org/genproto/googleapis/api/httpbody google.golang.org/genproto/googleapis/api/monitoredres google.golang.org/genproto/googleapis/api/annotations google.golang.org/genproto/googleapis/api/metric google.golang.org/genproto/googleapis/api/distribution google.golang.org/genproto/googleapis/api/label google.golang.org/genproto/googleapis/api/configchange google.golang.org/genproto/googleapis/api/serviceconfig google.golang.org/genproto/protobuf/api]: exit status 1: go: github.com/derekparker/delve@v1.0.0: module lookup disabled by GOPROXY=off
go: error loading module requirements


goroutine 1 [running]:
log.Panic(0xc0001aff58, 0x1, 0x1)
        /Users/jwhite/Documents/Code/go/src/log/log.go:333 +0xac
main.main()
        /Users/jwhite/go/pkg/mod/github.com/!one!of!one/struct2ts@v1.0.2/cmd/struct2ts/main.go:87 +0x2a6
exit status 2

```

**Comment by john8329** [comment]
Seems to be working now, apart from the anonymous structure thing, it can generate the code fine.
